### ISSUE TITLE
Connection resets upon evaluation on Windows for Janet + Netrepl

### ISSUE THREAD

**Issue by sogaiu** [Olical/conjure#532]
Currently, in a local Windows 10 environment, when editing a `.janet` file in Neovim with Conjure, with a netrepl connection established to the default host and port, evaluating a form (e.g. `(+ 1 2)`) results in:

```
127.0.0.1:9365 (ECONNRESET)
```

---

It appears that the netrepl server received an unexpected sequence of bytes and it [closed the existing connection](https://github.com/janet-lang/spork/blob/641b27238e073c5f5f963ec16c79b51643d3e66f/spork/netrepl.janet#L253-L259).

Specifically, the netrepl server was [expecting part of a message to be a sequence of bytes that could be handed to Janet's parser to produce a string](https://github.com/janet-lang/spork/blob/641b27238e073c5f5f963ec16c79b51643d3e66f/spork/netrepl.janet#L79-L81), but it received a Windows-style file-path with unescaped backslashes, e.g. `"C:\Windows\Temp\file.janet"`.  When such sequences of bytes are passed to Janet's parser the result is [this sort of error](https://github.com/janet-lang/janet/blob/cc5beda0d26c0b91fb28540291e950392cf59fc4/src/core/parse.c#L339) [1].

The following patch seems to lead to better behavior (at least in limited testing here):

```diff
diff --git a/fnl/conjure/client/janet/netrepl.fnl b/fnl/conjure/client/janet/netrepl.fnl
index 687f0928..af44e35b 100644
--- a/fnl/conjure/client/janet/netrepl.fnl
+++ b/fnl/conjure/client/janet/netrepl.fnl
@@ -56,7 +56,11 @@
     (with-conn-or-warn
       (fn [conn]
         (remote.send conn (.. "\xFF(parser/where (dyn :parser) " row " " col ")"))
-        (remote.send conn (.. "\xFEsource \"" file-path "\"") nil true)
+        (remote.send conn
+                     (.. "\xFEsource \""
+                         (string.gsub file-path "\\" "\\\\")
+                         "\"")
+                     nil true)
         (remote.send conn msg cb true)))))
 
 (defn connect [opts]
```

The idea is to replace each backslash character with two backslash characters.  I don't think that will break anything but perhaps I've not thought of certain cases (^^;

On a side note, although I would hope folks don't work with files that have backslashes in their names on non-Windows platforms, I think this patch would actually improve things for such situations.

Thanks to @pyrmont for review and discussion.

---

[1] The error message was observed after modifying the netrepl server's source to log various values.

**Comment by Olical** [comment]
Looks good and works for me on Linux, applied, compiled and pushed to `develop`. Let me know what you think!

**Comment by Olical** [comment]
A timing issue was discovered too! I've pushed a change to `develop` that prevents the user from sending code to the netrepl until it has successfully connected. It's not exactly how I'd like it right now, but should be more robust. I could never reproduce the timing issue but I can see how it might happen from the code.

**Comment by sogaiu** [comment]
Thanks for taking a look and updating.

Things were still not quite working, but after some trial and error, it appears that the following patch helps:

```diff
diff --git a/fnl/conjure/remote/netrepl.fnl b/fnl/conjure/remote/netrepl.fnl
index 53ec0f30..96aa3b44 100644
--- a/fnl/conjure/remote/netrepl.fnl
+++ b/fnl/conjure/remote/netrepl.fnl
@@ -52,10 +52,10 @@
                       (opts.on-failure err)
 
                       (do
+                        (send conn (or opts.name "Conjure"))
                         (conn.sock:read_start (client.schedule-wrap handle-message))
                         (opts.on-success)))))})))
 
-  (send conn (or opts.name "Conjure"))
   conn)
 
 ;; Example:
```

The reasoning behind this change is that the `(send ...)` might have been happening (for my slow Windows environment) before the callback [here](https://github.com/Olical/conjure/blob/d687f527dfd0e032dbb04caa5d0a779b8e66e383/fnl/conjure/remote/netrepl.fnl#L49-L56) was being executed.

Does that make sense?

I tried the change on a Linux box and it seemed to work there too.

**Comment by Olical** [comment]
Applied and checked on Linux and it's looking good to me! The logic of the issue makes sense too, great find! Thank you so much!
