### ISSUE TITLE
No syntax highlighting in log buffer when opening file using telescope.

### ISSUE THREAD

**Issue by lemonnuggets** [Olical/conjure#562]
When I open a file using either `nvim path/to/file` or using my file tree (tested with netrw and oil.nvim), the log buffer shows up with correct syntax highlighting. After this I can open other files however I wish and the log buffer shows up as required with syntax highlighting.
<img width="683" alt="image" src="https://github.com/Olical/conjure/assets/63046776/66e56a6c-35b0-43d2-bf1a-7e4c2efd308a">

The issue arises when I open neovim using either `nvim` or `nvim path/to/directory` and then use telescope to open a file. In this case the log buffer shows up as shown below, ie without syntax highlighting.
<img width="715" alt="image" src="https://github.com/Olical/conjure/assets/63046776/e3afdaa3-9b59-4c99-8580-c586399b4915">

Using `:LspInfo` I was able to find out that the lsp client I use for clojure (`clojure_lsp`) doesn't attach to the log buffer in this case.

Sorry for wasting your time if this issue isn't related to conjure. My reasoning for posting this here instead of `nvim-lsp` or something is that I'm facing facing this issue only in the conjure-log buffer. I tried opening `*.cljc` files and the lsp was attaching to the buffer as expected along with proper syntax highlighting so I think the issue must be with conjure. Not really all that proficient with the technicalities of neovim so I'm not sure how to proceed with debugging this so any pointers would also be appreciated.

**Comment by Olical** [comment]
Ah that's annoying, sorry about that. Can't say I've seen the same issue and I think it comes down to lazy package loading configuration. I don't use it for the most part because it causes so many issues and doesn't save me much time at all.

If you use `:e` inside the log buffer does the syntax highlighting then work fine?

**Comment by lemonnuggets** [comment]
`:e` doesn't seem to do anything other than clear the log buffer. New output is still lacking syntax highlighting.
I don't know if this information is helpful but I also tried `lazy = false` for conjure to see if that'd help but I didn't see any difference.
Is there anything I can try to figure out where the fault is? Could this issue be due to some differences in how telescope opens buffers? Which autocommand is being used to apply syntax highlighting to the log buffer? I could test a trivial config without conjure and see if there's some difference in how that autocommand is triggered when using telescope. Don't know if I'd be able to recreate it tbh.

**Comment by lemonnuggets** [comment]
Still facing this issue. Thought I'd see what events conjure had autocommands for and keep a log of when those events were being triggered using an autocommand of my own for logging. So far the only thing I've been able to observe is that whenever the syntax highlighting works, the `BufEnter` event has been triggered on the conjure-log file at some point and whenever it isn't triggered the syntax highlighting doesn't show up. 
I have also noticed that this doesn't just happen with telescope. While using the `mini.files` plugin when I open the file using `go_in`, the `BufEnter` event is triggered for conjure-log and syntax highlighting works but when opening the file using `go_in_plus`, the event isn't triggered and syntax highlighting doesn't work. I think I'll try to find out what the difference is in how both these methods open the file and that might help me figure out why this issue is happening.
If I could get some idea about how the conjure-log file is opened and when BufEnter is triggered on it that'd be helpful.

**Comment by Olical** [comment]
Sorry for the delay, I was on holiday. Interesting, it does sort of feel like it's another plugin interfering here. As far as I can remember and see in the source, Conjure doesn't care about BufEnter (other than one plugin) and we set up FileType autocmds for the filetypes we support and care about at the time (which can be adjusted through configuration).

Conjure doesn't set the language or syntax of the buffer, we let Neovim do that by relying on the existing configuration based on the file extension. Which is why each Conjure log buffer is called `conjure-log-$PID.$LANGUAGE_SPECIFIC_EXTENSION`, we let your personal editor config load that buffer as it would any other `.clj` / `.fnl` / `.lisp` etc.

So if something's stopping that buffer from opening normally I don't think I can get around it from my side.

https://github.com/Olical/conjure/blob/master/fnl/conjure/log.fnl

That file, `conjure.log`, is the place where we actually create the log window and buffer where required. So if there's some funny business it might be in there but I still don't see anything that would behave like this at a glance.

**Comment by lemonnuggets** [comment]
Hope you had a great holiday!
Glad to report that I've finally figured out what was wrong. Thanks to your suggestion about interfering plugins, I tried disabling plugins one-by-one till the bug was fixed. Turns out it was `nvim-lint` that was causing the problem for me. I had configured it to lint with an autocommand that was running on `BufEnter`. Not sure exactly why but debouncing the try_lint call seems to fix this issue.
In case anyone else also comes across this specific issue, here is my configuration for `nvim-lint` using [LazyVim](https://github.com/LazyVim/LazyVim/blob/cca2e091490fc87eafd7ee27a965e4cbcacdc012/lua/lazyvim/plugins/linting.lua#L3) as a reference.
```lua
local function debounce(ms, fn)
  local timer = vim.loop.new_timer()
  return function(...)
    local argv = { ... }
    timer:start(ms, 0, function()
      timer:stop()
      vim.schedule_wrap(fn)(unpack(argv))
    end)
  end
end

return {
  'mfussenegger/nvim-lint',
  event = {
    'BufReadPre',
    'BufNewFile',
  },
  dependencies = {
    'williamboman/mason.nvim',
  },
  config = function()
    -- required so nvim env includes linters installed by mason
    local mason = require 'mason'
    mason.setup()

    local lint = require 'lint'
    local linters = require 'config.linters'
    lint.linters_by_ft = linters

    local lint_augroup = vim.api.nvim_create_augroup('lint', {
      clear = true,
    })

    vim.api.nvim_create_autocmd({
      'BufWritePost',
      'BufReadPost',
      'InsertLeave',
    }, {
      group = lint_augroup,
      callback = debounce(10, function()
        lint.try_lint()
      end),
    })
  end,
}
```
Also sorry for wasting your time with an issue in my configuration and thanks for helping out anyway. I'll close this issue now.

**Comment by Olical** [comment]
So glad you worked it out! And not a problem, it was worth raising it so I
could take a look and give context.

**Comment by shaunlebron** [comment]
This happened to me, and still persisted after disabling all my plugins.  Updating to master fixed it.
